### ISSUE TITLE
Allow hexadecimal input

### ISSUE THREAD

**Issue by jackpot51** [redox-os/calc#10]
I think it would be useful, especially with bitwise operations, to allow hexadecimal input and output.

Basically, any number prepended with `0x` would be parsed as hexadecimal. All others would be decimal. If there is any input that is hexadecimal, then the output should be hexadecimal, and prepended with `0x`.

Examples:
`0x400 * 2 = 0x800`
`0x123 | 0x321 = 0x323`
`200 * 0x1 = 0xC8`

**Comment by mgmoens** [comment]
This could get tricky in regards to us using FP numbers to represent numbers. Trick is probably adding some extra info to the intermediate result to tell whatever is hosting the calc lib what kind of number we are talking about.

I think that a hex number times a float should be a float, but a hex number times a integral number should be a hex.

**Comment by huntergoldstein** [comment]
I think the easiest thing to do is adding a tag to the intermediate result, something like:
```rust
enum Format { Hex, Decimal, Binary }

impl Format {
  pub fn merge(self, other: Format, ...) -> Format {
    ...
  }
}
```
where `merge` knows how to reconcile if `self` is Hex and `other` is `Decimal` and so on. I'm not sure how idiomatic this is.

**Comment by huntergoldstein** [comment]
This has been all but done in the `hex` branch. There are two items of note:
-  Instead of having a `Format` tag I decided to add a `Value` enum; this is anticipating #3 
- Currently I've defined operations (`Add`, `Sub`, etc.) on IRs (IntermediateResults) instead of values. This seems somewhat silly so I plan to change that.
