### ISSUE TITLE
Chained functions don't work correctly in respect to division.

### ISSUE THREAD

**Issue by mgmoens** [redox-os/calc#11]
**Reproduction**:  try calculating log (4) / log (2).

**Expected behavior**: Calc should return 2.

**Actual behavior**: Calc returns 1.1234502189822873, which is the same as log ( 4 / log (2) ).

**Build information**: ` [shell]$ git rev-parse HEAD
a6398c1469922452eea52b4a3255e8dc1c0441a8`

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

**Comment by huntergoldstein** [comment]
That's most likely due to the changes in 681201cb2730770ea2e9c8c357dd89a5d6e5e76c; this can (and probably should) be changed by modifying the [`d_expr` here](https://github.com/redox-os/calc/blob/a6398c1469922452eea52b4a3255e8dc1c0441a8/src/lib.rs#L571) to `g_expr`, which will cause atoms to consume parenthesized expressions or number literals instead of a full expression.

**Comment by huntergoldstein** [comment]
Now function calls will bind as tight as possible versus before where they were as "loose" as possible, akin to existential / universal quantifiers in logic.
